version: '3.1'
services:
  app:
    ports:
      - 14445:14445
    build: .
    volumes:
      - ./app:/app      
  db_mysql:
    image: amd64/mysql:5.6
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db_mysql
    ports:
     - 8080:80
    environment:
      PMA_HOST: db_mysql
      UPLOAD_LIMIT: 300M

volumes:
  dbdata:
  db: